# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: 1950s
  theme_night: 
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'Dapr中文社区.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  copyright:
    notice: '© {year}. Dapr 中文社区版权所有'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/dapr-cn/dapr-cn-site'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: June 6, 2018
  citation_style: apa
